config/routes.rb
Rails.application.routes.draw do
  root 'repositories#index'
  resources :repositories do
    member do
      put :total_downloads
      put :hide
    end
    collection do
      get :search
      get 'tag/:tag' => :search_by_tag
  	end
  end
  resources :users
  get "/auth/:provider/callback" => "callbacks#create"
  get "/repositories/:id/favourite" => "repositories#favourite", :as => :repositories_favourite
  delete "/signout" => "callbacks#destroy", :as => :signout
end

app/models/repository.rb
class Repository < ApplicationRecord
  self.per_page = Settings.pagination.default
  is_impressionable
  scope :unhide_repos, -> { where(hide: false) }
  has_many :language_repositories, dependent: :destroy, inverse_of: :repository
  has_many :languages, through: :language_repositories, dependent: :destroy
  has_many :favourites, dependent: :destroy
  has_many :users, through: :favourites
  has_attached_file :poc_image, styles: { medium: "300x300>", thumb: "100x100>" },
                    default_url: :set_default_url,
                    url: "/system/:id/:style/:filename"
  accepts_nested_attributes_for :language_repositories
  validates_attachment_content_type :poc_image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  validates :description, presence: true, length: { maximum: 300 }

  #searching by tags using actastaggable gem
  acts_as_taggable
  acts_as_taggable_on :tags_for_repository

  after_initialize :create_repository_identicon
  after_create :clean_files

  def self.search(key_word, language)
    key_word = "%#{key_word.upcase}%"
    condition_for_key_word = "repositories.hide != true AND (UPPER(repositories.name) LIKE ? OR UPPER(author_name) LIKE ? OR UPPER(description) LIKE ?)"
    repositories = (['All', 'Filter by'].include?(language) || language.nil?) ? Repository.all : Language.find_by(name: language).repositories
    repositories = repositories.where(condition_for_key_word, key_word, key_word, key_word) if key_word.present?
    repositories
  end

  private

  def create_repository_identicon
      directory_name = "public/images"
      Dir.mkdir(directory_name) unless File.exists?(directory_name)
      RubyIdenticon.create_and_save(name, "public/images/#{name}.png")
  end

  def set_default_url
    "#{name}.png"
  end

  def clean_files
    path = "#{Rails.root}/public/images/#{name}.png"
    File.delete(path) if File.exist?(path)
  end
end

app/controllers/repositories_controller.rb
require 'will_paginate/array'
class RepositoriesController < ApplicationController
  before_action :change_in_own_repo, only: [:edit, :update, :destroy]
  def index
    @repositories = paginated(Repository.unhide_repos, params[:page])
  end

  def show
    @repository = initialize_repo
    @language_graph = LanguageGraphData.new(@repository).call
    impressionist(@repository, nil, { unique: [:session_hash] })
  end

  def new
    begin
      repository_values_result = Github::FetchRepo.new(params[:user_name], params[:repo_name], session[:github_token]).call
      @repository = Repository.new(repository_values_result[:repository_details])
      repository_values_result[:language].each do |language,code|
        new_language = Language.find_or_create_by(name: language)
        @repository.language_repositories.build(language_id: new_language.id, code: code, repository_id: @repository.id)
      end
      @language_graph = LanguageGraphData.new(@repository).call
    rescue => e
      flash[:red] = "Error: #{e}"
      redirect_to repositories_path
    end
  end

  def edit
    @repository = initialize_repo
    @language_graph = LanguageGraphData.new(@repository).call
  end

  def create
    @repository = Repository.new(repository_params)
    if @repository.save
      flash[:green] = "POC is created successfully..!"
      redirect_to repositories_path
    else
      flash[:red] = @repository.errors.full_messages.first
      redirect_back(fallback_location: new_repository_path(user_name: params[:repository][:author_name], repo_name: params[:repository][:name]))
    end
  end

  def update
    @repository = initialize_repo
    if @repository.update_attributes(repository_params)
      flash[:green] = "POC #{@repository.name} updated successfully..!"
      redirect_to repositories_path
    else
      flash[:red] = @repository.errors.full_messages.first
      redirect_back(fallback_location: new_repository_path(user_name: params[:repository][:author_name], repo_name: params[:repository][:name]))
    end
  end

  def favourite
    @repository = initialize_repo
    @message = ""
    if current_user.present?
      if current_user.is_favourited?(@repository)
        current_user.favourites.find_by_repository_id(params[:id]).destroy
        @message = "POC #{@repository.name} removed from your favourites..!"
      else
        current_user.favourites.build(repository_id: params[:id])
        current_user.save
        @message = "POC #{@repository.name} added to your favourites..!"
      end
    end
    respond_to do |format|
      format.js
      format.html { redirect_to :back }
    end
  end

  def destroy
    destroyed = initialize_repo.destroy
    flash[:green] = "POC Removed successfully..!" if destroyed
    @pocs = paginated(Repository.where(author_name: current_user.name), params[:poc_page])
    @repositories = Github::FetchAllRepos.new(current_user.name, session[:github_token]).call
    @repositories = filter_pocs(@repositories).paginate(per_page:1, page: params[:repo_page])
    redirect_to user_path(params[:user_id])
  end

  def search
    @repositories = paginated(Repository.search(params[:key_word].strip, params[:language]), params[:page])
  end

  def total_downloads
    repo = initialize_repo
    repo.no_of_downloads = repo.no_of_downloads.to_i + 1
    repo.save
  end

  def hide
    repository = initialize_repo
    repository.update_attribute(:hide, !repository.hide)
  end

  def search_by_tag
    @repositories = paginated(Repository.tagged_with(params[:tag]), params[:page])
    render :index
  end

  private

  def repository_params
    params.require(:repository).permit(:id, :author_name, :avatar_url, :repo_id,
                  :name, :description, :private, :download_link, :clone_url,
                  :git_url, :ssh_url, :svn_url, :no_of_stars, :no_of_watchers,
                  :no_of_downloads, :no_of_views, :no_of_bookmarks, :has_wiki,
                  :wiki_url, :repo_created_at, :last_updated_at, :poc_image,
                  :tag_list, language_repositories_attributes: [:id, :repository_id, :language_id , :code])
  end

  def initialize_repo
    Repository.find(params[:id])
  end

  def change_in_own_repo
    unless current_user.present? && initialize_repo.author_name == current_user.name
      flash[:red] = "You dont have permission to access that."
      redirect_to repositories_path
    end
  end
end

app/helpers/repositories_helper.rb
module RepositoriesHelper
  FAV_REPO_COLOR = "pink-text"
  UNFAV_REPO_COLOR = ""
  AVAILABLE_LOGOS = ["C", "CoffeeScript", "CSS", "HTML", "Java",
    "JavaScript", "Perl", "Rouge", "Ruby", "Shell", "Visual Basic"]

  def fav_repo(repo)
    if current_user.present? && current_user.is_favourited?(repo)
      FAV_REPO_COLOR
    else
      UNFAV_REPO_COLOR
    end
  end

  def languages_for_option
    language_options = ['Filter by', 'All']
    language_options << Language.pluck(:name).uniq.sort
    language_options = language_options.flatten
    options = language_options.zip(language_options)
    options.first.push({disabled: true, selected: true})
    options
  end

  def update_repo(description, tag_list )
    @repository.description = description
    @repository.tag_list = tag_list
  end

  def hidden_fields_array
    [:avatar_url, :name, :private, :download_link, :clone_url, :git_url, :ssh_url, :author_name,
     :svn_url, :no_of_stars, :no_of_watchers, :has_wiki, :wiki_url, :repo_created_at,
     :last_updated_at, :no_of_downloads, :no_of_views, :no_of_bookmarks, :description, :tag_list]
  end

  def display_tag
    tags = ""
    @repository.tag_list.each do |tag|
      tags += "<div class='chip'>#{tag}</div>"
    end
    tags.html_safe
  end

  def highest_used_language(repository)
    if repository.languages.present?
      language = repository.language_repositories.sort_by{|l| l.code}.last.language.name
      image = AVAILABLE_LOGOS.include?(language) ? language : "Default"
      {language: language, image: image}
    else
      {language: "No language", image: "Default"}
    end
  end

  def useful_counts
    counts = {
      repository_count: Repository.count,
      user_count: User.count,
      language_count: Language.count
    }
  end
end

app/views/repositories/_favourite_repo.html.erb
<%= link_to repositories_favourite_path(repository), remote: true, class: "fav-icon tooltipped", data: { position: 'top', delay: '50', tooltip: 'Favourite this POC' } do %>
  <i class="fa fa-heart <%= fav_repo(repository) %>" aria-hidden="true"></i>
  <%= repository.favourites.count %>
<% end %>
<script>
  $('.tooltipped').tooltip({delay: 50});
</script>

app/views/repositories/_form.html.erb
<div id="repository_preview" hidden=true>
  <%= render partial: 'repository_preview' %>
</div>
<main>
  <section class="repository-details">
    <div class="container z-depth-1" id="repository_update">
      <div class="row body-content">
        <div class="col s12">
          <div class="add-repo-body">
            <div class="top-bg">
            </div>
            <div class="repo-content">
              <div class="repo-img" onclick="Common.triggerPOCImage();">
                <span>
                  <%= image_tag @repository.poc_image, class: "responsive-img z-depth-1", id: "image" %>
                </span>
                <!-- <div class="overlay">
                  <h2>Image</h2>
                  <p>EDIT</p>
                </div> -->
              </div>
              <h1 class="center-align"><%= @repository.name.titleize %></h1>
              <div class="row" id="form-design">
                <div class="input-field col m6 s12">
                  <textarea id="description" class="materialize-textarea">
                    <%= @repository.description %>
                  </textarea>
                  <label for="description">Description</label>
                </div>
                <div class="input-field col m6 s12">
                  <input type="text" data-role="materialtags" value="<%= @repository.tag_list.to_s %>" id="tag_list">
                  <label for="chips">Tags</label>
                </div>
                <div class="input-field col s12 center-align">
                  <button class="btn waves-effect" type="submit" name="action" id="btn_preview">
                    Preview
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</main>

<script>
  $(document).ready(function () {
    if ($('#description')[0].value != "") {
      $('#description').focus();
    }

    $("#tag_list").on('keyup', function (e) {
      Common.displayTags(e);
    });

    $("#btn_preview").on('click',function () {
      Common.displayPreview();
    });

    $("#poc_image").on('change',function (e) {
      var file = this.files[0];
      Common.uploadImage(e, file);
    });

    $('.chips-placeholder').material_chip({placeholder: 'Enter a tag', secondaryPlaceholder: '+Tag'});
  });
</script>

app/views/repositories/_language_fields.html.erb
<%= f.hidden_field :repository_id %>
<%= f.hidden_field :language_id %>
<%= f.hidden_field :code %>

app/views/repositories/_repositories_view.html.erb
<div id='repositories_section'>
  <% @repositories.each do |repository| %>
    <!-- new card start -->
    <div class="card hoverable" >
      <div class="card-image waves-effect waves-block waves-light">
        <%= link_to(repository) do %>
        <%= image_tag repository.poc_image, alt: "", class: "responsive-img wp-post-image" %>
        <% end %>
      </div>
      <div class="card-content">
        <h4 class="card-title">
          <%= link_to repository.name, repository_path(repository) %>
        </h4>
        <p class="user">
          <a href="https://github.com/<%= repository.author_name %>" target="_blank">
            <%= repository.author_name %>
          </a>
        </p>
        <p class="desc">
          <%= repository.description[0, 50] %>
          <%= link_to  "...", repository_path(repository) if (repository.description.length > 50)%>
        </p>
        <ul class="action-icons">
          <li class="tech">
            <%= image_tag "language_icons/#{highest_used_language(repository)[:image]}.png",
                alt: "Language Logo", class: "tooltipped",
                data: { position: "top", delay: "50", tooltip: highest_used_language(repository)[:language] } %>
          </li>
          <li class="fav right-align">
              <a class="tooltipped" data-position="top" data-delay="50" data-tooltip="views">
                <i class="fa fa-eye" aria-hidden="true"></i>
                <%= repository.impressions.count %>
              </a>
            <span id="fav_repo_<%= repository.id %>">
              <%= render partial: "favourite_repo", locals: { repository: repository } %>
            </span>
          </li>
        </ul>
      </div>
    </div>
  <% end %>
  <% if !@repositories.present? && (params[:page] == 1 || params[:page].nil?) %>
    <h4><center>No Records Found</center></h4>
  <% end %>
</div>
<script>
  var nextPage,
    previousPage;
  previousPage = 0;
  nextPage = <%= @repositories.next_page %>
  $(window).on('scroll', function () {
    Common.showRepositoriesOnScroll();
  });

  $(document).ready(function () {
    $('.tooltipped').tooltip({delay: 50});
    Common.cardArrange();
  });
</script>

app/views/repositories/_repository_preview.html.erb
<main>
  <section class="repository-details">
    <div class="container z-depth-1">
      <div class="row body-content">
        <div class="col s12">
          <div class="repo-content-body">
            <div class="top-bg">
            </div>
            <div class="repo-content">
              <div class="repo-img">
                <span>
                  <%= image_tag @repository.poc_image,
                    class: "responsive-img z-depth-1", id: "image_preview"  %>
                </span>
              </div>
              <h1 class="center-align"><%= @repository.name.titleize %></h1>
              <p class="center-align update-text">by
                <a href="https://github.com/<%= @repository.author_name %>" target="_blank">
                  <%= @repository.author_name %>
                </a>
                / last updated on
                <%= time_ago_in_words(@repository.last_updated_at) %>
                ago
              </p>
              <div id="display_tags" class="center-align"></div>
              <p class="description center-align" id="p_decription"></p>
              <div class="icons-row">
                <ul class="left-icons">
                  <li class="tooltipped" data-position="left" data-delay="50" data-tooltip="Stars">
                    <i class="fa fa-star" aria-hidden="true"></i>
                    <%= @repository.no_of_stars.to_i %>
                  </li>
                  <li class="tooltipped" data-position="left" data-delay="50" data-tooltip="Fork">
                    <i class="fa fa-code-fork" aria-hidden="true"></i>
                    <%= @repository.no_of_forks.to_i %>
                  </li>
                  <li class="tooltipped" data-position="left" data-delay="50" data-tooltip="Watchers">
                    <i class="fa fa-bell" aria-hidden="true"></i>
                    <%= @repository.no_of_watchers.to_i %>
                  </li>
                  <li class="tooltipped" data-position="left" data-delay="50" data-tooltip="Downloads">
                    <i class="fa fa-download" aria-hidden="true"></i>
                    <%= @repository.no_of_downloads.to_i %>
                  </li>
                  <li class="tooltipped" data-position="left" data-delay="50" data-tooltip="Views">
                    <i class="fa fa-eye" aria-hidden="true"></i>
                    <%= @repository.impressions.count.to_i %>
                  </li>
                  <li class="tooltipped" data-position="left" data-delay="50" data-tooltip="Favourites">
                    <i class="fa fa-bookmark" aria-hidden="true"></i>
                    <%= @repository.favourites.count.to_i %>
                  </li>
                </ul>
              </div>
              <div class="data-column">
                <% if @language_graph[0] == "No languages used." %>
                  <div id="barchart_values" class="left-column">No languages used.</div>
                <% else %>
                  <div id="barchart_values" class="left-column"></div>
                <% end %>
                <div class="right-column">
                  <ul>
                    <li>
                      <%= link_to "#{ @repository.svn_url }", class: "waves-effect", target: "_blank" do %>
                        <i class="fa fa-github"></i>
                        GitHub Page
                      <% end %>
                    </li>
                    <li>
                      <%= link_to "#{ @repository.wiki_url }", class: "waves-effect", target: "_blank" do %>
                        <i class="fa fa-file-text-o"></i>
                        GitHub Wiki
                      <% end %>
                    </li>
                    <li>
                      <%= link_to "#{ @repository.download_link }", onclick: "increment_downloads(#{@repository.id});" do %>
                        <i class="fa fa-download"></i>
                        Download
                      <% end %>
                    </li>
                  </ul>
                </div>
              </div>
              <div class="center-align">
                <%= form_for @repository do |f| %>
                  <%= f.hidden_field :id %>
                  <%= f.file_field :poc_image, id: 'poc_image' ,accept:'image/*', hidden: true %>
                  <% hidden_fields_array.each do |field| %>
                    <%= f.hidden_field field %>
                  <% end %>

                  <%= f.fields_for :language_repositories do |builder| %>
                    <%= render 'language_fields', :f => builder %>
                  <% end %>
                  <%= f.submit "#{@repository.new_record? ? 'publish' : 'save'}", class: "btn waves-effect"%>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</main>
<script type="text/javascript">
  google.charts.load("current", {packages: ["corechart"]});
  google.charts.setOnLoadCallback(drawChart);

  function drawChart() {
    <% if @language_graph[0] == "No languages used." %>
      var no_graph = 'No_languages_used';
    <% else %>
      array_data = <%= raw @language_graph %>
      var graph_style = [["Language", "Percentage", {role: "style"}]];

      for (var lg = 0; lg < array_data.length; lg++) {
        graph_style.push(array_data[lg]);
      }

      var data = google.visualization.arrayToDataTable(graph_style);
      var view = new google.visualization.DataView(data);
      view.setColumns([
        0,
        1, {
          calc: "stringify",
          sourceColumn: 1,
          type: "string",
          role: "annotation"
        },
        2
      ]);

      var options = {
        title: "Language used in percentage",
        width: 350,
        height: 300,
        bar: {
          groupWidth: "15%"
        },
        legend: {
          position: "none"
        }
      };
      var chart = new google.visualization.BarChart(document.getElementById("barchart_values"));
      chart.draw(view, options);
    <% end %>
  }
</script>

app/views/repositories/_search_form.html.erb
<%= form_tag("/repositories/search/", method: :get, remote: true, id: searchform) do %>
  <div class="row">
    <div class="input-field col s4">
      <%= select_tag 'language', options_for_select(languages_for_option),
        onchange: "Common.searchRepoByLanguage(#{searchform})" %>
    </div>
    <div class="input-field col s8">
      <%= text_field_tag 'key_word', nil, placeholder: "search",
       class: "searchbox", style: "color:black;", id: keyword, title: "Enter to search", onkeyup: "Common.searchRepoByKeyword(#{searchform}, #{keyword})" %>
    </div>
  </div>
  <input type="submit" hidden=true onclick="Common.scrollTopOnSearch(<%= searchform %>);">
<% end %>

app/views/repositories/destroy.js.erb
Materialize.toast('<%= @message %>', 4000, 'green');
$("#repos_and_pocs").html("<%= escape_javascript(render partial: 'users/repos_and_pocs', locals: { pocs: @pocs, repositories: @repositories } ) %>");

app/views/repositories/edit.html.erb
<%= render 'form' %>

app/views/repositories/favourite.js.erb
<% if @message.present? %>
  Materialize.toast("<%= @message %> <a href='javascript:;' onclick='closeToast();'><i class='material-icons close'>close</i></a>", 4000, 'green');
<% end %>
$("#fav_repo_<%= @repository.id %>").html("<%= escape_javascript(render partial: 'repositories/favourite_repo', locals: {repository: @repository}) %>");
function closeToast() {
  $('.green').remove();
};
<% unless current_user.present? %>
  Materialize.toast("Please login first <a href='javascript:;' onclick='closeToast();'><i class='material-icons close'>close</i></a>", 4000, 'red');
<% end %>

app/views/repositories/index.html.erb
<main>
  <section class="bg-section">
    <div class="container fullheight">
      <div class="row valign-wrapper green-bg">
        <div class="col s12 valign center-align">
          <h1>Connect &bull; Add &bull; Share</h1>
          <p>Show off your research and development</p>
          <p>Open Source your knowledge and make better community for today and tomorrow</p>
          <% unless current_user.present? %>
            <a href="/auth/github" class="git-btn waves-effect btn-large">
              <i class="fa fa-github" aria-hidden="true"></i>
              Signup with GitHub
            </a>
          <% end %>
          <div class="row">
            <%= render partial: 'search_form', locals: { searchform: 'index_search', keyword: 'index_keyword' } %>
          </div>
          <div class="row">
            <div class="col s12 m4">
              <h4><i class="fa fa-code" aria-hidden="true"></i>
                <%= useful_counts[:repository_count] %>+ Projects
              </h4>
            </div>
            <div class="col s12 m4">
              <h4><i class="fa fa-users" aria-hidden="true"></i>
                <%= useful_counts[:user_count] %>+ Contributers
              </h4>
            </div>
            <div class="col s12 m4">
              <h4><i class="fa fa-language" aria-hidden="true"></i>
                <%= useful_counts[:language_count] %>+ Languages
              </h4>
            </div>
            <div class="col s12">
              <a href="javascript:;" id="listing" class="down-arrow"><i class="fa fa-angle-down" aria-hidden="true"></i></a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <section class="repositories-listing">
    <div class="container">
      <div id="freewall">
        <%= render partial: 'repositories_view', locals: { repositories: @repositories } %>
        <input type="hidden" id="loaded_page" value="">
      </div>
    </div>
  </section>
</main>
<script>
  window.onload = Common.showSearchOnScroll();
  $(document).ready(function () {
    Common.selectDropdown();
    Common.showHideGreenBg();
  });
</script>

app/views/repositories/new.html.erb
<%= render 'form' %>

app/views/repositories/preview.js.erb
$('#repository_form').hide();
$('#repository_preview').show();
$('#repository_preview').html("<%= escape_javascript(render partial: 'repository_preview',locals: {repository: @repository}) %>");

app/views/repositories/search.js.erb
<% if  params[:append] == "true" %>
$("#repositories_section").append("<%= escape_javascript(render partial: 'repositories_view', locals: { repositories: @repositories } ) %>");
<% else %>
$("#repositories_section").html("<%= escape_javascript(render partial: 'repositories_view', locals: { repositories: @repositories } ) %>");
<% end %>

app/views/repositories/show.html.erb
<main>
  <section class="repository-details">
    <div class="container z-depth-1">
      <div class="row body-content">
        <div class="col s12">
          <div class="repo-content-body">
            <div class="top-bg">
            </div>
            <div class="repo-content">
              <div class="repo-img">
                <span>
                  <%= image_tag @repository.poc_image, class: "responsive-img z-depth-1" %>
                </span>
              </div>
              <h1 class="center-align"><%= @repository.name.titleize %></h1>
              <p class="center-align update-text">by
                <a href="https://github.com/<%= @repository.author_name %>" target="_blank">
                  <%= @repository.author_name %>
                </a>
                / last updated on
                <%= time_ago_in_words(@repository.last_updated_at) %>
                ago
              </p>
              <span id="fav_repo_<%= @repository.id %>" class="fav-icon-link">
                <%= render partial: "favourite_repo", locals: { repository: @repository } %>
              </span>
              <div class="center-align">
                <% @repository.tag_list.each do |tag| %>
                  <span class="chip waves-effect">
                    <a href="/repositories/tag/<%= tag %>"><%= tag %></a>
                  </span>
                <% end %>
              </div>
              <p class="description center-align"><%= @repository.description %></p>
              <div class="icons-row">
                <ul class="left-icons">
                  <li class="tooltipped" data-position="left" data-delay="50" data-tooltip="Stars">
                    <i class="fa fa-star" aria-hidden="true"></i>
                    <%= @repository.no_of_stars.to_i %>
                  </li>
                  <li class="tooltipped" data-position="left" data-delay="50" data-tooltip="Fork">
                    <i class="fa fa-code-fork" aria-hidden="true"></i>
                    <%= @repository.no_of_forks.to_i %>
                  </li>
                  <li class="tooltipped" data-position="left" data-delay="50" data-tooltip="Watchers">
                    <i class="fa fa-bell" aria-hidden="true"></i>
                    <%= @repository.no_of_watchers.to_i %>
                  </li>
                  <li class="tooltipped" data-position="left" data-delay="50" data-tooltip="Downloads">
                    <i class="fa fa-download" aria-hidden="true"></i>
                    <%= @repository.no_of_downloads.to_i %>
                  </li>
                  <li class="tooltipped" data-position="left" data-delay="50" data-tooltip="Views">
                    <i class="fa fa-eye" aria-hidden="true"></i>
                    <%= @repository.impressions.count.to_i %>
                  </li>
                  <li class="tooltipped" data-position="left" data-delay="50" data-tooltip="Favourites">
                    <i class="fa fa-bookmark" aria-hidden="true"></i>
                    <%= @repository.favourites.count.to_i %>
                  </li>
                </ul>
                <%= social_share_button_tag(repository_url(@repository), desc: @repository.name) %>
              </div>
              <div class="data-column">
                <% if @language_graph[0] == "No languages used." %>
                  <div id="barchart_values" class="left-column">No languages used.</div>
                <% else %>
                  <div id="barchart_values" class="left-column"></div>
                <% end %>
                <div class="right-column">
                  <ul>
                    <li>
                      <%= link_to "#{ @repository.svn_url }", class: "waves-effect", target: "_blank" do %>
                        <i class="fa fa-github"></i>
                        GitHub Page
                      <% end %>
                    </li>
                    <li>
                      <%= link_to "#{ @repository.wiki_url }", class: "waves-effect", target: "_blank" do %>
                        <i class="fa fa-file-text-o"></i>
                        GitHub Wiki
                      <% end %>
                    </li>
                    <li>
                      <%= link_to "#{ @repository.download_link }", onclick: "increment_downloads(#{@repository.id});" do %>
                        <i class="fa fa-download"></i>
                        Download
                      <% end %>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</main>
<script type="text/javascript">
  google.charts.load("current", {packages: ["corechart"]});
  google.charts.setOnLoadCallback(drawChart);
  var graphWidth = 350;
  if($(window).width() < 480)
  {
    graphWidth= 250;
  }
  function drawChart() {
    <% if @language_graph[0] == "No languages used." %>
      var no_graph = 'No_languages_used';
    <% else %>
      array_data = <%= raw @language_graph %>
      var graph_style = [["Language", "Percentage", { role: "style" } ]];

      for (var lg = 0; lg < array_data.length; lg++) {
        graph_style.push(array_data[lg]);
      }

      var data = google.visualization.arrayToDataTable(graph_style);
      var view = new google.visualization.DataView(data);
      view.setColumns([
        0,
        1, {
          calc: "stringify",
          sourceColumn: 1,
          type: "string",
          role: "annotation"
        },
        2
      ]);
      var options = {
        title: "Language used in percentage",
        width: graphWidth,
        height: 300,
        bar: {
          groupWidth: "15%"
        },
        legend: {
          position: "none"
        }
      };
      var chart = new google.visualization.BarChart(document.getElementById("barchart_values"));
      chart.draw(view, options);



      $('#barchart_values div').css('width', '100%');
    <% end %>
  }

  function increment_downloads(repo_id) {
    $.ajax({
      type: "put",
      url: '/repositories/' + repo_id + '/total_downloads'
    })
  }
</script>