config/routes.rb
Rails.application.routes.draw do
  root 'repositories#index'
  resources :repositories do
    member do
      put :total_downloads
      put :hide
    end
    collection do
      get :search
      get 'tag/:tag' => :search_by_tag
  	end
  end
  resources :users
  get "/auth/:provider/callback" => "callbacks#create"
  get "/repositories/:id/favourite" => "repositories#favourite", :as => :repositories_favourite
  delete "/signout" => "callbacks#destroy", :as => :signout
end

app/models/user.rb
class User < ApplicationRecord
  scope :subscribed_users, -> { where(subscribed: true) }
  has_many :favourites
  has_many :repositories, through: :favourites

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["nickname"]
      user.email = auth["info"]["email"]
      user.avtar_url = auth["info"]["image"]
      user.github_url = auth["info"]["urls"]["GitHub"]
    end
  end

  def is_favourited?(repository)
    favourites.find_by_repository_id(repository.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  ASSOCIATIVE_COLUMNS = ['impressions', 'favourites']
  before_filter :authorize, only: [:show]
  
  def show
    pocs = Repository.where(author_name: current_user.name)
    repositories = Github::FetchAllRepos.new(current_user.name, session[:github_token]).call
    favourite_pocs = Repository.find(current_user.favourites.pluck(:repository_id)) if current_user.favourites.present?
    @pocs = sort_data(pocs, params[:column], params[:poc_sorting], params[:poc_page], ASSOCIATIVE_COLUMNS.include?(params[:column]))
    @repositories = sort_data(filter_pocs(repositories), "name", params[:repo_sorting], params[:repo_page])
    @favourite_pocs = sort_data(favourite_pocs, "name", params[:favourite_poc_sorting], params[:favourite_poc_page])
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def sorting_link(column, table)
    sorting_order = (params[:column] == column) ? toggle_order(params["#{table}_sorting"]) : "ASC"
    link_to(icon_for_sorting(sorting_order), user_path(params[:id], column: column,
     "#{table}_sorting" => sorting_order), remote: true,
      class: 'waves-effect list-order active tooltipped',
      data: { position: 'top', delay: '50', tooltip: "sort by #{column}" })
  end

  def toggle_order(order)
    order == "ASC" ? "DESC" : "ASC"
  end

  def icon_for_sorting(order)
    "<i class='fa fa-sort-amount-#{order.downcase}' aria-hidden='true'></i>".html_safe
  end

  def serial_no(page_no, index)
    page_no ||= 1
    (page_no.to_i - 1) * Settings.pagination.default + index + 1
  end
end

app/views/users/_favourite_poc_table.html.erb
<% if @favourite_pocs.present? %>
  <table class="striped responsive-table tables-data favourite-poc-data">
    <tr>
      <th>No.</th>
      <th>Name <%= sorting_link("name", "favourite_poc") %></th>
      <th>Downloads <%= sorting_link("no_of_downloads", "favourite_poc") %></th>
      <th>Views <%= sorting_link("impressions", "favourite_poc") %></th>
      <th>Favourites <%= sorting_link("favourites", "favourite_poc") %></th>
    </tr>

    <% @favourite_pocs.each_with_index do |poc, index| %>
    <tr>
      <td><%= serial_no(params[:favourite_poc_page], index) %></td>
      <td><%= poc.name %></td>
      <td><%= poc.no_of_downloads.to_i %></td>
      <td><%= poc.impressions.count.to_i %></td>
      <td><%= poc.favourites.count.to_i %></td>
    </tr>
    <% end %>
  </table>
  <div class="tables-paging center-align">
    <%= will_paginate @favourite_pocs, param_name: 'favourite_poc_page',
      previous_label: pagination[:previous_label],
      next_label: pagination[:next_label]  %>
  </div>
<% else %>
  <h6 class="no-record">No Records found</h6>
<% end %>
<script>
  $('.tooltipped').tooltip({delay: 50});
</script>

app/views/users/_poc_table.html.erb
<% if @pocs.present? %>
  <table class="striped responsive-table tables-data pocs-data">
    <tr>
      <th>No.</th>
      <th>Name <%= sorting_link("name", "poc") %></th>
      <th>Downloads <%= sorting_link("no_of_downloads", "poc") %></th>
      <th>Views <%= sorting_link("impressions", "poc") %></th>
      <th>Favourites <%= sorting_link("favourites", "poc") %></th>
      <th>Show/Hide</th>
      <th>Actions</th>
    </tr>

    <% @pocs.each_with_index do |poc, index| %>
    <tr>
      <td><%= serial_no(params[:poc_page], index) %></td>
      <td><%= poc.name %></td>
      <td><%= poc.no_of_downloads.to_i %></td>
      <td><%= poc.impressions.count.to_i %></td>
      <td><%= poc.favourites.count.to_i %></td>
      <td>
        <div class="switch">
          <label>
            <input type="checkbox" onchange="Common.showOrHideRepo('<%= hide_repository_path(poc.id) %>')" <%= "checked" if poc.hide %>>
            <span class="lever"></span>
          </label>
        </div>
      </td>
      <td>
        <%= link_to edit_repository_path(poc.id), class: "action-links waves-effect tooltipped",
         data: { turbolinks: false, position: 'top', delay: '50', tooltip: "edit" }  do %>
          <i class="fa fa-pencil" aria-hidden="true"></i>
        <% end %>
        <%= link_to repository_path(poc.id, user_id: params[:id]), method: :delete,
         class: "action-links waves-effect tooltipped", data: { confirm: 'Are you sure?', position: 'top', delay: '50', tooltip: "delete" } do %>
          <i class="fa fa-trash" aria-hidden="true"></i>
        <% end %>
      </td>
    </tr>
    <% end %>

  </table>
  <div class="tables-paging center-align">
    <%= will_paginate @pocs, param_name: 'poc_page',
      previous_label: pagination[:previous_label], next_label: pagination[:next_label] %>
  </div>
<% else %>
  <h6 class="no-record">No Records found</h6>
<% end %>
<script>
  $('.tooltipped').tooltip({delay: 50});
</script>

app/views/users/_repos_and_pocs.html.erb
<main>
  <section class="repository-details">
    <div class="container z-depth-1">
      <div class="row body-content">
        <div class="col s12">
          <ul class="tabs dashboard-tabs">
            <li class="tab col s3 waves-effect waves-green">
              <a class="active" href="#poc_table">POCs</a>
            </li>
            <li class="tab col s3 waves-effect waves-green">
              <a href="#repo_table">GitHub Repositories</a>
            </li>
            <li class="tab col s3 waves-effect waves-green">
              <a href="#favourite_poc_table">Favourite POCs</a>
            </li>
          </ul>
        </div>
        <div id="poc_table" class="col s12">
          <%= render partial: "users/poc_table", locals: { pocs: @pocs } %>
        </div>
        <div id="repo_table" class="col s12">
          <%= render partial: "users/repository_table", locals: { repositories: @repositories } %>
        </div>
        <div id="favourite_poc_table" class="col s12">
          <%= render partial: "users/favourite_poc_table", locals: { repositories: @favourite_pocs } %>
        </div>
      </div>
    </div>
  </section>
</main>
<script>
  $(document).ready(function(){
    $('ul.tabs').tabs();
  });
  $('.pagination > a').attr('data-remote', 'true');
  $('.tooltipped').tooltip({delay: 50});
</script>

app/views/users/_repository_table.html.erb
<% if @repositories.present? %>
  <table class="striped responsive-table tables-data git-repo-data">
    <tr>
      <th>No.</th>
      <th>Name <%= sorting_link("name", "repo") %></th>
      <th>Add Repo</th>
    </tr>

    <% @repositories.each_with_index do |repo, index| %>
    <tr>
      <td><%= serial_no(params[:repo_page], index) %></td>
      <td><%= repo["name"] %></td>
      <td>
        <%= link_to new_repository_path(user_name: current_user.name, repo_name: repo["name"]),
         class: "action-links waves-effect tooltipped", data: { turbolinks: false, position: 'top', delay: '50', tooltip: "Add repository" } do %>
          <i class="fa fa-plus" aria-hidden="true"></i>
        <% end %>
      </td>
    </tr>
    <% end %>
  </table>
  <div class="tables-paging center-align">
    <%= will_paginate @repositories, param_name: 'repo_page',
      previous_label: pagination[:previous_label],
      next_label: pagination[:next_label] %>
  </div>
<% else %>
  <h6 class="no-record">No Records found</h6>
<% end %>
<script>
  $('.tooltipped').tooltip({delay: 50});
</script>

app/views/users/index.html.erb
<% if current_user %>
  Welcome
  <%= image_tag(current_user.avtar_url) %>
  <%= current_user.name %>
  <%- @repositories.each do |repo| %>
    <li><a href= <%= repo["html_url"] %>>
      <%= repo["name"] %>
    </a></li>
  <% end %>
  <%= link_to('Logout', signout_path, :method => :delete) %>
<% else %>
  <li>
  <%= link_to("Sign in with Github", "/auth/github")  %>
  </li>
<% end %>

app/views/users/new.html.erb
<section class="z-depth-1" id="splash-blue">
  <div class="container">
    <div class="row">
      <div id="payoff" class="col s12 center-align">
        <h1 class="white-text main-title">Connect. Add. Share.</h1>
        <h5 class="white-text sub-title">Show off your research and development<br>
        open source your knowledge and make better community for today and tomorrow</h5>
        <!-- <h5 class="white-text sub-title">Create APIs, service based apps &amp; high value integrations in a few clicks</h5> -->
      </div>
    </div>
    <div class="row github_login">
      <a href="/auth/github" class="waves-effect waves-light btn white text-primarycolor modal-trigger"><i class="fa fa-github" style="color: #689f38 !important"></i></i> SIGN UP WITH GITHUB</a>
      <a href="/auth/bitbucket" class="waves-effect waves-light btn white text-primarycolor modal-trigger"><i class="fa fa-bitbucket" style="color: #689f38 !important"></i></i> SIGN UP WITH BITBUCKET</a>
    </div>
    <div class="row">
      <form method="get" action="/search" id="search">
        <input name="q" type="text" size="40" placeholder="Search..." /><span class="fa fa-search"></span></input>
      </form>
    </div>
    <div class="row" style="text-align: center">
      <div class="col s4 ">
        <h5 class="white-text sub-title">1111+ Projects</h5>
      </div>
      <div class="col s4">
        <h5 class="white-text sub-title">1111+ Contributers</h5>
      </div>
      <div class="col s4">
        <h5 class="white-text sub-title">40+ Languages</h5>
      </div>
    </div>
  </div>
</section>
<h1>Users#new</h1>
<% if current_user %>
  <li>
    Welcome <%= current_user.name %>
    <%= link_to('Logout', signout_path, :method => :delete) %>
  </li>
<% else %>
  <li>
  <%= link_to("Sign in with Github", "/auth/github")  %>
  <%= link_to("Sign in with Bitbucket", "/auth/bitbucket")  %>
  </li>
<% end %>

app/views/users/show.html.erb
<main class="no-padding">
  <div id="repos_and_pocs">
    <%= render partial: "repos_and_pocs", locals: { pocs: @pocs, repositories: @repositories } %>
  </div>
</main>

app/views/users/show.js.erb
$("#poc_table").html("<%= escape_javascript(render partial: 'poc_table', locals: { pocs: @pocs } ) %>");
$("#repo_table").html("<%= escape_javascript(render partial: 'repository_table', locals: { repositories: @repositories } ) %>");
$("#favourite_poc_table").html("<%= escape_javascript(render partial: 'favourite_poc_table', locals: { favourite_pocs: @favourite_pocs } ) %>");
$('.pagination > a').attr('data-remote', 'true');