config/routes.rb
Rails.application.routes.draw do
  root 'repositories#index'
  resources :repositories do
    member do
      put :total_downloads
      put :hide
    end
    collection do
      get :search
      get 'tag/:tag' => :search_by_tag
  	end
  end
  resources :users
  get "/auth/:provider/callback" => "callbacks#create"
  get "/repositories/:id/favourite" => "repositories#favourite", :as => :repositories_favourite
  delete "/signout" => "callbacks#destroy", :as => :signout
end

app/views/layouts/_footer.html.erb
<footer class="page-footer">
  <div class="container">
    <div class="row">
      <div class="col m6 s12">
        &copy;
        <a href="">CodeForest</a>
        - Powered by
        <a href="">BoTree Technologies</a>
      </div>
      <div class="col m6 s12 footer-links">
        <ul>
          <li>
            <a href="">About</a>
          </li>
          <li>
            <a href="">FAQ</a>
          </li>
          <li>
            <a href="">Privacy Policy</a>
          </li>
          <li>
            <a href="">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="navbar-fixed">
    <nav>
      <div class="container nav-wrapper">
        <%= link_to repositories_path, class: "brand-logo" do %>
          <span><%= image_tag "logo.png" %></span>
          <span>Code Forest</span>
        <% end %>
        <ul class="right menu">
          <li>
            <div class="row" id="search_fields">
              <% if params[:action] == 'index' && params[:controller] == 'repositories' %>
                <%= render partial: 'search_form',
                  locals: { searchform: 'header_search', keyword: 'header_keyword' } %>
              <% end %>
            </div>
          </li>
          <% unless current_user.present? %>
          <li>
            <a href="/auth/github">
              <i class="fa fa-sign-in" aria-hidden="true"></i>
              GitHub Login
            </a>
          </li>
          <% else %>
          <li>
            <a class="dropdown-button user-pic" data-activates="child-menu">
              <%= image_tag current_user.avtar_url, size: Settings.user_image.size %>
              <i class="fa fa-caret-down right" aria-hidden="true"></i>
            </a>
          </li>
        </ul>
        <ul id="child-menu" class="dropdown-content">
          <li class="user-profile">
            <%= image_tag current_user.avtar_url, size: Settings.user_image.size %>
            <h4><%= current_user.name %></h4>
          </li>
          <li>
            <%= link_to user_path(current_user.id), data: { no_turbolink: true } do %>
              <i class="fa fa-tachometer" aria-hidden="true"></i>
              Dashboard
            <% end %>
          </li>
          <li>
            <%= link_to signout_path, method: :delete do %>
              <i class="fa fa-sign-in fa-rotate-180" aria-hidden="true"></i>
              Logout
            <% end %>
          </li>
        </ul>
        <% end %>
      </div>
    </nav>
  </div>
</header>
<script>
  $(document).ready(function () {
    Common.selectDropdown();
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <title>CodeForest</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>

  <body data-gr-c-s-loaded="true">
    <%= render partial: 'layouts/header'%>
    <% flash.each do |key, message| %>
      <script>Materialize.toast("<%= message%> <a href='javascript:;' onclick='closeToast();'><i class='material-icons close'>close</i></a>", 4000, '<%= key %>');</script>
    <% end %>
    <%= yield %>
    <%= render partial: 'layouts/footer'%>
  </body>
</html>
<script>
  $( document ).ajaxStart(function() {
    $.blockUI({ message: "<h6>please wait...</h6>" });
  });

  $( document ).ajaxStop(function() {
    $.unblockUI();
  });

  $(document).ready(function(){
    $('.tooltipped').tooltip({delay: 50});
  });

  function closeToast() {
    $('.green, .red, .notice').remove();
  };
</script>